### ISSUE TITLE
sitename extraction

### ISSUE THREAD

**Issue by sobir-git** [adbar/trafilatura#183]
I would like to report a bug.
```python3
from trafilatura.metadata import extract_metadata

metadata = extract_metadata('<html><head><title> - Home</title></head><body/></html>')
```
Exception:
```
Traceback (most recent call last):
  File "/home/ailab_user/sobir/mmde-notebooks/scripts/extraction/bug-report.py", line 3, in <module>
    metadata = extract_metadata('<html><head><title> - Home</title></head><body/></html>')
  File "/home/ailab_user/miniconda3/envs/mmde-processing/lib/python3.9/site-packages/trafilatura/metadata.py", line 465, in extract_metadata
    metadata.sitename = extract_sitename(tree)
  File "/home/ailab_user/miniconda3/envs/mmde-processing/lib/python3.9/site-packages/trafilatura/metadata.py", line 333, in extract_sitename
    if '.' in mymatch.group(1):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by adbar** [comment]
Hi @sobir-git, thanks, that's a bug indeed.
