### ISSUE TITLE
Executable with trafilatura module not working?

### ISSUE THREAD

**Issue by Rapid1898-code** [adbar/trafilatura#249]
Hello - i have the following working code with the trafilatura-module -

```
import trafilatura as traf
url = traf.fetch_url("https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_b439762c2fb1cc0a92457f4214601e58")
workText = traf.extract(url)    
print(workText)
```

When i create the windows-executeable with
`pyinstaller --onefile test.py`

i get the following error message when running the exe:

```
G:\DEV\Fiverr\TRY\raghav_one>test.exe
Traceback (most recent call last):
  File "configparser.py", line 790, in get
  File "collections\__init__.py", line 986, in __getitem__
  File "collections\__init__.py", line 978, in __missing__
KeyError: 'min_file_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    url = traf.fetch_url("https://www.cnn.com/europe/live-news/russia-ukraine-war-news-09-13-22/h_b439762c2fb1cc0a92457f4214601e58")
  File "trafilatura\downloads.py", line 155, in fetch_url
  File "trafilatura\downloads.py", line 123, in _handle_response
  File "configparser.py", line 819, in getint
  File "configparser.py", line 809, in _get_conv
  File "configparser.py", line 804, in _get
  File "configparser.py", line 793, in get
configparser.NoOptionError: No option 'min_file_size' in section: 'DEFAULT'
[7540] Failed to execute script 'test' due to unhandled exception!
```
Any idea why this is happening?
Do i have to use any other parameters when creating the exe?

**Comment by Rapid1898-code** [comment]
With this command it works
`pyinstaller --onefile --collect-data trafilatura test.py`
