### ISSUE TITLE
Error when running executable on MacOS?

### ISSUE THREAD

**Issue by Rapid1898-code** [adbar/trafilatura#264]
Hello - i have the following code  - which works fine on MacOs when running in the terminal

```
import trafilatura as traf
if __name__ == '__main__':
  url = traf.fetch_url("http://www.goodfoodgroup.com")
  workText = traf.extract(url)    
  print(workText)
```

But when i create an executeable using pyinstaller (v 5.6.2) and start the program. I get the following error-message:

```
PolziMacs-Mini:~ polzimac$ /Users/polzimac/Documents/DEV/Python-Diverses/Trafilatura/exmpl2 ; exit;
Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "collections/__init__.py", line 941, in __getitem__
  File "collections/__init__.py", line 933, in __missing__
KeyError: 'min_file_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exmpl2.py", line 4, in <module>
  File "trafilatura/downloads.py", line 156, in fetch_url
  File "trafilatura/downloads.py", line 124, in _handle_response
  File "configparser.py", line 818, in getint
  File "configparser.py", line 808, in _get_conv
  File "configparser.py", line 803, in _get
  File "configparser.py", line 792, in get
configparser.NoOptionError: No option 'min_file_size' in section: 'DEFAULT'
[32845] Failed to execute script 'exmpl2' due to unhandled exception!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

Why is this not working when i created an executeable with pyinstaller?

**Comment by adbar** [comment]
I'm not sure why that happens, these lines are thoroughly tested. The problem is probably on your side, I'd say you need to include the settings file into the package.

**Comment by Rapid1898-code** [comment]
Hello - thanks for the reply.
What do you mean with "you need to include the settings file into the package"?
Currently i am creating the executeables using the command
`pyinstaller --onefile exmpl2.py`

**Comment by Rapid1898-code** [comment]
Hello - with this command it seems to work now fine:
`pyinstaller --onefile --collect-datas=trafilatura exmpl2.py`
Thanks!

**Comment by Rapid1898-code** [comment]
Hello - with this command it seems to work now fine:
`pyinstaller --onefile --collect-datas=trafilatura exmpl2.py`
Thanks!
