### ISSUE TITLE
Missing title crashes Trafilatura

### ISSUE THREAD

**Issue by rgeronimi** [adbar/trafilatura#29]
In some web pages Trafilatura crashes with this error:
```
Traceback (most recent call last):
  File "/Users/raphaelgeronimi/Local/Sabrina/python_libraries/extractpost.py", line 99, in _extract_html_with
    include_comments=False)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/core.py", line 649, in extract
    max_tree_size=max_tree_size, url_blacklist=url_blacklist
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/core.py", line 562, in bare_extraction
    docmeta = extract_metadata(tree, url, date_extraction_params)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/metadata.py", line 371, in extract_metadata
    metadata['sitename'] = extract_sitename(tree)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/site-packages/trafilatura/metadata.py", line 302, in extract_sitename
    mymatch = re.search(r'^.*?[-|]\s+(.*)$', tree.find('.//head/title').text)
  File "/usr/local/Caskroom/miniconda/base/envs/myenv/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

Reading the code, it seems that the reason is that in metadata.py line 302, the code in bold below returns None, which triggers an exception in the search method of the re library:
mymatch = re.search(r'^.*?[-|]\s+(.*)$', **tree.find('.//head/title').text**)

The solution would be to check for None (which could alter the logic afterward).

**Comment by adbar** [comment]
Yes, thank you, just fixed in 9b649d84a9b6f79ea29ff612b46e9730fa0557b9.
