### ISSUE TITLE
XMLSyntaxError during conversion to XML output

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#375]
Error url: `https://www.tristatetelecom.com/productdetailI2.aspx?dataid=IPGSM-4G`

Error: 

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-17-95f098a4decc>"](https://localhost:8080/#), line 2, in <cell line: 2>
    content_source1 = trafilatura.extract(ssss, output_format='xml', include_comments=False)

  File "/usr/local/lib/python3.10/dist-packages/trafilatura/core.py", line 1091, in extract
    return determine_returnstring(document, output_format, include_formatting, tei_validation)

  File "/usr/local/lib/python3.10/dist-packages/trafilatura/core.py", line 788, in determine_returnstring
    returnstring = control_xml_output(output, output_format, tei_validation, document)

  File "/usr/local/lib/python3.10/dist-packages/trafilatura/xml.py", line 106, in control_xml_output
    output_tree = fromstring(control_string, CONTROL_PARSER)

  File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring

  File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument

  File "src/lxml/parser.pxi", line 1796, in lxml.etree._parseDoc

  File "src/lxml/parser.pxi", line 1085, in lxml.etree._BaseParser._parseUnicodeDoc

  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError

  File "<string>", line 2
XMLSyntaxError: Failed to parse QName 'padding:', line 2, column 480

Function: `trafilatura.extract(source, output_format='xml', include_comments=False)`

**Comment by vbarbaresi** [comment]
I extracted a minimal reproducing example
```
echo 'Testing<ul style="" padding:1px; margin:15px""><b>Features:</b> <li>Saves the cost of two dedicated phone lines.</li> al station using Internet or cellular technology.</li> <li>Requires no change to the existing Fire Alarm Control Panel configuration. The IPGSM-4G connects directly to the primary and secondary telephone ports.</li>
' | trafilatura --xml
```

We need a long enough element not to be dropped, and then `padding:1px; margin:15px` are invalid attributes: the `:` symbol prefix doesn't match any XML namespace.

I proposed a fix in https://github.com/adbar/trafilatura/pull/462
