### ISSUE TITLE
Error when multiproessing

### ISSUE THREAD

**Issue by fortyfourforty** [adbar/trafilatura#420]
The use case:
I'm using multiprocessing and trafilatura to scrape and extract data.

The problem:
cannot pickle 'lxml.etree._ListErrorLog' object

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
lxml.etree.XPathEvalError: Error in xpath expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 211, in _sendback_result
    result_queue.put(_ResultItem(work_id, result=result,
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'lxml.etree._ListErrorLog' object
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
[<ipython-input-9-c6903bf6079a>](https://localhost:8080/#) in <cell line: 2>()
      1 # scrape_all_domains()
----> 2 scrape_all_urls()



5 frames
[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

TypeError: cannot pickle 'lxml.etree._ListErrorLog' object
```

**Comment by adbar** [comment]
As far as I can see this error is not related to Trafilatura. Multiprocessing indeed implies that objects can be pickled, you need to use something else that these lxml objects.
