### ISSUE TITLE
Few issues with tests.

### ISSUE THREAD

**Issue by majcl** [adbar/trafilatura#454]
I have a question, what is the envrionment you run tests now? When i tried to run them on python3.8, i have a several issues:
1) when testing resiliparse:  the line 
     `decoded = bytes_to_str(htmlstring, detect_encoding(htmlstring))`
    requires that htmlstring is of type bytes, however its **mostly** string. So this fails. Maybe the problem is with resiliparse version, but the version installed is the one i got from dependencies.
    Maybe something like 
    ```
    if instanceof(htmlstring, bytes):
       do_the_decoding_stuff
   ```
    will be needed?
    
2) There are complains when running tests:
`Warning: node executable not found, reverting to pure-Python mode. Install Node.js v10 or newer to use Readability.js.`
I have tried to install nodejs, but then tests fails horribly.
Probably would be better to write to readme, one should ignore this warning.

3) There are tons of following tracebacks:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/boilerpy3/extractors.py", line 108, in parse_doc
    bp_parser.feed(input_str)
  File "/usr/local/lib/python3.8/site-packages/boilerpy3/parser.py", line 657, in feed
    HTMLParser.feed(self, data)
  File "/usr/local/lib/python3.8/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.8/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.8/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/lib/python3.8/site-packages/boilerpy3/parser.py", line 667, in handle_endtag
    self.end_element(tag)
  File "/usr/local/lib/python3.8/site-packages/boilerpy3/parser.py", line 495, in end_element
    self.label_stacks.pop()
IndexError: pop from empty list
```
Though test continues to run. Im not sure, its ok, or not?

4) It seems that test dependencies are not installable on python 3.11 and newer. Maybe it could be written in README.
  At least i was trying official python:3.11 and python:3.12 docker images

**Comment by adbar** [comment]
Hi @majcl, I did not run the tests for a while, the last time I checked it worked.

1. Certain packages need to be updated or certain lines changed over time, that's normal. Your suggestion makes sense.
2. Managing Python and Node side-by-side is cumbersome, it could be on your system or it could be that it doesn't work (anymore).
3. I also got the `IndexError: pop from empty list` in the past, there's nothing to do about it, a `try/except` is needed here.
4. I have no idea if all dependencies work on Python 3.11 and newer, that goes beyond the scope of the tests. If the packages are not updated I will simply omit them.

Feel free to draft a pull request, it would help!
